"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.redactSSN = exports.redactCreditCard = exports.redactIP = exports.redactPhone = exports.redactEmail = exports.maskSensitiveFields = exports.sanitizeObject = exports.sanitizePII = exports.createCorrelationContext = exports.extractTraceId = exports.extractRequestId = exports.generateSpanId = exports.generateTraceId = exports.generateRequestId = exports.LogLevel = exports.createLogger = exports.Logger = void 0;
var logger_1 = require("./logger");
Object.defineProperty(exports, "Logger", { enumerable: true, get: function () { return logger_1.Logger; } });
Object.defineProperty(exports, "createLogger", { enumerable: true, get: function () { return logger_1.createLogger; } });
var types_1 = require("./types");
Object.defineProperty(exports, "LogLevel", { enumerable: true, get: function () { return types_1.LogLevel; } });
var requestId_1 = require("./requestId");
Object.defineProperty(exports, "generateRequestId", { enumerable: true, get: function () { return requestId_1.generateRequestId; } });
Object.defineProperty(exports, "generateTraceId", { enumerable: true, get: function () { return requestId_1.generateTraceId; } });
Object.defineProperty(exports, "generateSpanId", { enumerable: true, get: function () { return requestId_1.generateSpanId; } });
Object.defineProperty(exports, "extractRequestId", { enumerable: true, get: function () { return requestId_1.extractRequestId; } });
Object.defineProperty(exports, "extractTraceId", { enumerable: true, get: function () { return requestId_1.extractTraceId; } });
Object.defineProperty(exports, "createCorrelationContext", { enumerable: true, get: function () { return requestId_1.createCorrelationContext; } });
var sanitize_1 = require("./sanitize");
Object.defineProperty(exports, "sanitizePII", { enumerable: true, get: function () { return sanitize_1.sanitizePII; } });
Object.defineProperty(exports, "sanitizeObject", { enumerable: true, get: function () { return sanitize_1.sanitizeObject; } });
Object.defineProperty(exports, "maskSensitiveFields", { enumerable: true, get: function () { return sanitize_1.maskSensitiveFields; } });
Object.defineProperty(exports, "redactEmail", { enumerable: true, get: function () { return sanitize_1.redactEmail; } });
Object.defineProperty(exports, "redactPhone", { enumerable: true, get: function () { return sanitize_1.redactPhone; } });
Object.defineProperty(exports, "redactIP", { enumerable: true, get: function () { return sanitize_1.redactIP; } });
Object.defineProperty(exports, "redactCreditCard", { enumerable: true, get: function () { return sanitize_1.redactCreditCard; } });
Object.defineProperty(exports, "redactSSN", { enumerable: true, get: function () { return sanitize_1.redactSSN; } });
//# sourceMappingURL=index.js.map